apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-on-track-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-on-track-api
  template:
    metadata:
      labels:
        app: back-on-track-api
    spec:
      containers:
        - name: back-on-track-api
          image: matancyrus/back-on-track:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"