apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-on-track-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-on-track-frontend
  template:
    metadata:
      labels:
        app: back-on-track-frontend
    spec:
      initContainers:
      - name: wait-for-api
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z -w 2 back-on-track-api-service 8000; do echo "waiting for api..."; sleep 2; done']
      containers:
        - name: back-on-track-frontend
          image: matancyrus/back-on-track-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
          - name: frontend
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
            readOnly: false
      volumes:
      - name: frontend
        configMap:
          name: frontend-config