pipeline {
    agent {
        kubernetes {
            defaultContainer 'python'
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: python:3.12-alpine
      command:
        - cat
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      
    - name: kubectl
      image: alpine/k8s:1.30.0
      command:
        - cat
      tty: true
'''
        }
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        DOCKERHUB_REPO = "matancyrus/back-on-track"
        DEPLOYMENT_NAME = "back-on-track-api"
        CONTAINER_NAME = "back-on-track-api"
        K8S_NAMESPACE = "testing"
    }
    stages {
        stage('Prepare Tools') {
            steps {
                sh '''
                    apk add --no-cache git
                    python --version
                    git --version
                    pip install -r "app/requirements.txt"
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // This stage is necessary to avoid "fatal: detected dubious ownership in repository at /workspace" error
        stage('Trust git repository') {
            steps {
                sh '''
                    git config --global --add safe.directory '*'
                '''
            }

        }
        stage('Show Commit') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }

                echo "Current commit short SHA: ${env.IMAGE_TAG}"
            }
        }

        stage('Validate Python App') {
            steps {
                sh '''
                    python -m compileall .
                '''
            }
        }
        stage('liveness test') {
            steps {
                sh '''
                    set -eux
                    pytest -vv
                '''
            }

        }
        stage('Build and Push Image with Kaniko') {
            steps {
                container('kaniko') {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKERHUB_USERNAME',
                        passwordVariable: 'DOCKERHUB_PASSWORD'
                    )]) {
                        sh '''
                            set -eux

                            echo "Workspace is: $WORKSPACE"
                            echo "Docker image will be: $DOCKERHUB_REPO:$IMAGE_TAG"

                            mkdir -p /kaniko/.docker

                            AUTH="$(printf "%s:%s" "$DOCKERHUB_USERNAME" "$DOCKERHUB_PASSWORD" | /busybox/base64 | /busybox/tr -d '\\n')"

                            printf '{"auths":{"https://index.docker.io/v1/":{"auth":"%s"}}}\\n' "$AUTH" > /kaniko/.docker/config.json

                            /kaniko/executor \
                            --context "$WORKSPACE/app" \
                            --dockerfile "$WORKSPACE/app/Dockerfile" \
                            --destination "$DOCKERHUB_REPO:$IMAGE_TAG"
                        '''
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                container('kubectl') {
                    sh '''
                        set -eux

                        echo "Deploying image: $DOCKERHUB_REPO:$IMAGE_TAG"
                        kubectl set image deployment/$DEPLOYMENT_NAME \
                        $CONTAINER_NAME=$DOCKERHUB_REPO:$IMAGE_TAG \
                        -n $K8S_NAMESPACE

                        kubectl rollout status deployment/$DEPLOYMENT_NAME \
                        -n $K8S_NAMESPACE
                    '''
                }
            }
        }
        }

    post {
        success {
            echo "Pipeline completed successfully."
            echo "Image pushed: ${env.DOCKERHUB_REPO}:${env.IMAGE_TAG}"
        }

        failure {
            echo "Pipeline failed. Check the failed stage."
        }
    }
}